#Use the official Python Image from the Docker Hub
from python:3.9-slim

#Set the working Directory.
WORKDIR /app

# Install necessary packages listed in requirements.txt, if present
COPY requirements.txt .
RUN pip install -r requirements.txt

#Copy the current directory contents into the container at ./app
COPY . /app

#Install ant needed packages specified in the requirements.txt
RUN pip install flask

# Make port 5000 available to the world outside the container
Expose 5000

# Run app.py when the container launches
CMD ["python","app.py"]