# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements.txt first to install dependencies
COPY requirements.txt .

# Install necessary packages listed in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY . /app

# Make port 5000 available to the world outside the container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]
